/*
 * KAY_program.c
 *
 *  Created on: Aug 15, 2023
 *      Author: User
 */
/* ------------ INCLUDES ------------*/
#include "C:\Users\User\Desktop\iti\interfasing\grad's project\master_\LIB\std_types.h"
#include "C:\Users\User\Desktop\iti\interfasing\grad's project\master_\LIB\bit_math.h"
#include"KAY_interface.h"
#include"KAY_config.h"
#include "C:\Users\User\Desktop\iti\interfasing\grad's project\master_\MCAL\DIO\DIO_interface.h"
#include"util/delay.h"




void KEYPAD_INITIAL(){
	DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_PIN0,INPUT);
	DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_PIN1,INPUT);
	DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_PIN2,INPUT);
	DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_PIN3,INPUT);
	DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_PIN4,OUTPUT);
	DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_PIN5,OUTPUT);
	DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_PIN6,OUTPUT);
	DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_PIN7,OUTPUT);

}



u8 KEYPAD_GETKEY(void){

	u8 LOCAL_PRESSEDKEY=KEYPAD_NOTPRESSED;
	u8 LOCAL_KEYPAD_ARR[KEYPAD_ROW_NUM][KEYPAD_COLOUMN_NUM]=KEYPAD_ARR;
	u8 LOCAL_COLOUMN_INDEX=0,LOCAL_ROW_INDEX=0;
	u8 LOCAL_COLOUMN_ARR[KEYPAD_COLOUMN_NUM]={KEYPAD_COLOUMN0,KEYPAD_COLOUMN1,KEYPAD_COLOUMN2,KEYPAD_COLOUMN3};
	u8 LOCAL_ROW_ARR[KEYPAD_ROW_NUM]={KEYPAD_ROW0,KEYPAD_ROW1,KEYPAD_ROW2,KEYPAD_ROW3};
	u8 LOCAL_STATE=0;
	DIO_set_port_value(KEYPAD_PORT,0xF0);

	for(LOCAL_COLOUMN_INDEX=0;LOCAL_COLOUMN_INDEX<KEYPAD_COLOUMN_NUM;LOCAL_COLOUMN_INDEX++){

		DIO_set_pin_value(KEYPAD_PORT,LOCAL_COLOUMN_ARR[LOCAL_COLOUMN_INDEX],LOW);

		for(LOCAL_ROW_INDEX=0;LOCAL_ROW_INDEX<KEYPAD_ROW_NUM;LOCAL_ROW_INDEX++){

			DIO_get_pin_value(KEYPAD_PORT,LOCAL_ROW_ARR[LOCAL_ROW_INDEX],&LOCAL_STATE);

					if(LOCAL_STATE==LOW){

						while(LOCAL_STATE==0){

							DIO_get_pin_value(KEYPAD_PORT,LOCAL_ROW_ARR[LOCAL_ROW_INDEX],&LOCAL_STATE);

						}

						LOCAL_PRESSEDKEY=LOCAL_KEYPAD_ARR[LOCAL_ROW_INDEX][LOCAL_COLOUMN_INDEX];

						return LOCAL_PRESSEDKEY;

					}
				}

		DIO_set_pin_value(KEYPAD_PORT,LOCAL_COLOUMN_ARR[LOCAL_COLOUMN_INDEX],HIGH);

			}

			return LOCAL_PRESSEDKEY;
		}





































/*
void keypad_initial()
{
DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_ROW0,INPUT);
DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_ROW1,INPUT);
DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_ROW2,INPUT);
DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_ROW3,INPUT);
DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_COLOUMN0,OUTPUT);
DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_COLOUMN1,OUTPUT);
DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_COLOUMN2,OUTPUT);
DIO_set_pin_direction(KEYPAD_PORT,KEYPAD_COLOUMN3,OUTPUT);


}

u8 KEYPAD_GETKEY(void){

	u8 LOCAL_PRESSEDKEY=KEYPAD_NOTPRESSED;
	u8 LOCAL_KEYPAD_ARR[KEYPAD_ROW_NUM][KEYPAD_COLOUMN_NUM]=KEYPAD_ARR;
	u8 LOCAL_COLOUMN_INDEX=0,LOCAL_ROW_INDEX=0;
	u8 LOCAL_COLOUMN_ARR[KEYPAD_COLOUMN_NUM]={KEYPAD_COLOUMN0,KEYPAD_COLOUMN1,KEYPAD_COLOUMN2,KEYPAD_COLOUMN3};
	u8 LOCAL_ROW_ARR[KEYPAD_ROW_NUM]={KEYPAD_ROW0,KEYPAD_ROW1,KEYPAD_ROW2,KEYPAD_ROW3};
	u8 LOCAL_STATE=0;
	DIO_set_port_value(KEYPAD_PORT,0xf0);

	for(LOCAL_COLOUMN_INDEX=0;LOCAL_COLOUMN_INDEX<KEYPAD_COLOUMN_NUM;LOCAL_COLOUMN_INDEX++){
    DIO_set_pin_value(KEYPAD_PORT,LOCAL_COLOUMN_ARR[LOCAL_COLOUMN_INDEX],LOW);


		for(LOCAL_ROW_INDEX=0;LOCAL_ROW_INDEX<KEYPAD_ROW_NUM;LOCAL_ROW_INDEX++){

			DIO_get_pin_value(KEYPAD_PORT,LOCAL_ROW_ARR[LOCAL_ROW_INDEX],&LOCAL_STATE);

			if(LOCAL_STATE==LOW){

				while(LOCAL_STATE==LOW){

               DIO_get_pin_value(KEYPAD_PORT,LOCAL_ROW_ARR[LOCAL_ROW_INDEX],&LOCAL_STATE);

				}

				LOCAL_PRESSEDKEY=LOCAL_KEYPAD_ARR[LOCAL_ROW_INDEX][LOCAL_COLOUMN_INDEX];

				return LOCAL_PRESSEDKEY;

			}
		}


	}

	return LOCAL_PRESSEDKEY;
}


*/



























